export enum ParkActionTypes {
  PARK_GET_REQUEST = 'PARK_GET_REQUEST',
  PARK_GET_SUCCESS = 'PARK_GET_SUCCESS',
  PARK_GET_FAIL = 'PARK_GET_FAIL',

  PARK_SAVE_FAVORITES_REQUEST = 'PARK_SAVE_FAVORITES_REQUEST',
  PARK_SAVE_FAVORITES_SUCCESS = 'PARK_SAVE_FAVORITES_SUCCESS',
  PARK_SAVE_FAVORITES_FAIL = 'PARK_SAVE_FAVORITES_FAIL',

  PARK_SAVE_VISITEDS_REQUEST = 'PARK_SAVE_VISITEDS_REQUEST',
  PARK_SAVE_VISITEDS_SUCCESS = 'PARK_SAVE_VISITEDS_SUCCESS',
  PARK_SAVE_VISITEDS_FAIL = 'PARK_SAVE_VISITEDS_FAIL',

  PARK_SAVE_PRIORITIES_REQUEST = 'PARK_SAVE_PRIORITIES_REQUEST',
  PARK_SAVE_PRIORITIES_SUCCESS = 'PARK_SAVE_PRIORITIES_SUCCESS',
  PARK_SAVE_PRIORITIES_FAIL = 'PARK_SAVE_PRIORITIES_FAIL',

  PARK_SAVE_NOTIFICATION_REQUEST = 'PARK_SAVE_NOTIFICATION_REQUEST',
  PARK_SAVE_NOTIFICATION_SUCCESS = 'PARK_SAVE_NOTIFICATION_SUCCESS',
  PARK_SAVE_NOTIFICATION_FAIL = 'PARK_SAVE_NOTIFICATION_FAIL',

  PARK_CANCEL_NOTIFICATION_REQUEST = 'PARK_CANCEL_NOTIFICATION_REQUEST',
  PARK_CANCEL_NOTIFICATION_SUCCESS = 'PARK_CANCEL_NOTIFICATION_SUCCESS',
  PARK_CANCEL_NOTIFICATION_FAIL = 'PARK_CANCEL_NOTIFICATION_FAIL',

  PARK_SAVE_RESET = 'PARK_SAVE_RESET',
}